# Generated by Django 5.0 on 2025-11-19 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('party_size', models.PositiveIntegerField(help_text='Number of people', validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, help_text='Booking duration in hours', max_digits=3)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurants.table')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['table', 'booking_date', 'status'], name='bookings_bo_table_i_ab4b74_idx'), models.Index(fields=['restaurant', 'booking_date'], name='bookings_bo_restaur_96c7cf_idx')],
            },
        ),
    ]
